#

MAINTAINER=	s199p.wa1k9r@gmail.com
MASTERDIR=	${.CURDIR}/../u-boot-master

MODEL=		nanopi-neo2
BOARD_CONFIG=	nanopi_neo2_defconfig
FAMILY=		allwinner64

UBOOT_ARCH=     aarch64
EXTRA_PATCHES=  ${.CURDIR}/files/

.include "${MASTERDIR}/Makefile"

