#

#MASTERDIR=	${.CURDIR}/../u-boot-master
MASTERDIR=      ${.CURDIR}/../u-boot-2019.10-rc3

MODEL=		rock-pi-4
BOARD_CONFIG=	rock-pi-4-rk3399_defconfig
FAMILY=		rk3399

EXTRA_PATCHES=	${.CURDIR}/files/

.include "${MASTERDIR}/Makefile"
