# $FreeBSD: head/sysutils/u-boot-nanopi-k1-plus/Makefile 456178 2017-12-12 18:06:35Z s199p.wa1k9r $

MAINTAINER=	s199p.wa1k9r@gmail.com

MASTERDIR=	${.CURDIR}/../u-boot-2018.09

MODEL=		nanopi-k1-plus
BOARD_CONFIG=	nanopi_k1_plus_defconfig
FAMILY=		allwinner64

UBOOT_ARCH=     aarch64
EXTRA_PATCHES=  ${.CURDIR}/files/

.include "${MASTERDIR}/Makefile"

