#

MASTERDIR=	${.CURDIR}/../u-boot-2019.10-rc3
#MASTERDIR=	${.CURDIR}/../u-boot-master

MODEL=		khadas-edge-v
BOARD_CONFIG=	khadas-edge-v-rk3399_defconfig
FAMILY=		rk3399

EXTRA_PATCHES=  ${.CURDIR}/files/

.include "${MASTERDIR}/Makefile"
