# 

MASTERDIR=      ${.CURDIR}/../u-boot-2020.08

MODEL=		rock-pi-n10
BOARD_CONFIG=	rock-pi-n10-rk3399pro_defconfig
FAMILY=		rk3399

EXTRA_PATCHES=	${.CURDIR}/files/

PATCHFILES+=    \
		1333119/raw \
		1333120/raw \
		1333121/raw \
		1333123/raw \
		1333125/raw \
		1333126/raw \
		1333127/raw \
		1333128/raw \
		1333129/raw \
		1333130/raw \
		1333131/raw \
		1333132/raw 

.include "${MASTERDIR}/Makefile"

