# 

MASTERDIR=      ${.CURDIR}/../u-boot-2020.07

MODEL=		rock-pi-n10
BOARD_CONFIG=	rock-pi-n10-rk3399pro_defconfig
FAMILY=		rk3399

EXTRA_PATCHES=	${.CURDIR}/files/

PATCHFILES+=    1325139/raw \
		1325140/raw \
		1325141/raw \
		1325142/raw \
		1325143/raw \
		1325144/raw \
		1325145/raw

.include "${MASTERDIR}/Makefile"

