# $FreeBSD$

MASTERDIR=      ${.CURDIR}/../u-boot-2020.07

MODEL=		nanopi-r4s
BOARD_CONFIG=	nanopi-r4s-rk3399_defconfig
FAMILY=		rk3399

EXTRA_PATCHES=	${.CURDIR}/files/

.include "${MASTERDIR}/Makefile"
