# $FreeBSD: head/sysutils/u-boot-pinebookpro/Makefile 532960 2020-04-25 16:39:31Z manu $

MASTERDIR=	${.CURDIR}/../u-boot-2020.07

MODEL=		pinebook-pro
BOARD_CONFIG=	pinebook-pro-rk3399_defconfig
FAMILY=		rk3399

EXTRA_PATCHES=	${.CURDIR}/files/

.include "${MASTERDIR}/Makefile"

