#
# $FreeBSD$
#

MASTERDIR=	${.CURDIR}/../u-boot-2020.07

MODEL=		helios64
BOARD_CONFIG=	helios64-rk3399_defconfig
FAMILY=		rk3399

EXTRA_PATCHES=  ${.CURDIR}/files/

.include "${MASTERDIR}/Makefile"

