# $FreeBSD$
#
    COMMENT = System utilities

#   SUBDIR += u-boot-master-v2.4
    SUBDIR += u-boot-helios64-2020.07
    SUBDIR += u-boot-khadas-edge-v-2020.07
    SUBDIR += u-boot-nanopc-t4-2020.07
    SUBDIR += u-boot-nanopi-r4s-2020.07
    SUBDIR += u-boot-pinebook-pro-2020.07
    SUBDIR += u-boot-roc-rk3399-pc-plus-2020.07
    SUBDIR += u-boot-rock-pi-4-2020.07
    SUBDIR += u-boot-rock-pi-4c-2021.01
    SUBDIR += u-boot-rock-pi-e-2020.07
    SUBDIR += u-boot-rock-pi-n10-2020.07

.include <bsd.port.subdir.mk>
